### ISSUE TITLE
Failing 'peerDependency' for knex

### ISSUE THREAD

**Issue by NoLdman** [knex/knex-utils#126]
## Description

The 'package.json' of this project references `"knex": "^0.95.4"` as it's peer dependency, which is far behind the current stable release of [v2.1.0](https://github.com/knex/knex/releases/tag/2.1.0).  

## Workaround

Use parameter [legacy-peer-deps](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps) if you run NPM v7 or higher: `npm install --legacy-peer-deps`

---

***Note:** Unfortunately I currently do not have access to a Linux machine with a set-up Docker Environment, therefore I couldn't run the Jest test-suite against knex v2.1.0, but in my NodeJS application it seems to work fine with knex v2.1.0.*

**Comment by kibertoad** [comment]
Thank you for reporting this! Will fix

**Comment by kibertoad** [comment]
Release in 5.5.1

**Comment by kibertoad** [comment]
@NoLdman Can you confirm that 5.5.1 works correctly for you?

**Comment by NoLdman** [comment]
Thanks, works like a charm!! 😃 

On a side-note, I didn't dig fully into it, but spotted:

> sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning.

on the "[Coverage (16.x)](https://github.com/knex/knex-utils/runs/6625464161?check_suite_focus=true#logs)" report and just wanted to mention that I made a heartbeat-check with a sqLite-DB + Node v16 on my local application and it works flawlessly. :)
